version: '3.8'

services:
  discovery-server:
    build: ./discovery-server
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  user-service-1:
    build: ./user-service
    environment:
      - SERVER_PORT=8081
      - DISCOVERY_SERVER_URL=http://discovery-server:8080
    ports:
      - "8081:8081"
    depends_on:
      discovery-server:
        condition: service_healthy

  user-service-2:
    build: ./user-service
    environment:
      - SERVER_PORT=8083
      - DISCOVERY_SERVER_URL=http://discovery-server:8080
    ports:
      - "8083:8083"
    depends_on:
      discovery-server:
        condition: service_healthy

  call-service:
    build: ./call-service
    environment:
      - DISCOVERY_SERVER_URL=http://discovery-server:8080
      - SERVER_PORT=8082
    ports:
      - "8082:8082"
    depends_on:
      discovery-server:
        condition: service_healthy